sudo: false
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
#  - 5.3 doesn't provide a 'php' webserver as required in tests/api/run.sh
install:
  - composer self-update
  - composer install
addons:
  apt:
    packages:
    - xsltproc
script:
  - make clean
  - make check_permissions
  - make test
  - sh tests/api/run.sh
